import { lang } from './lang.svelte';

/** UI copy (chrome, not lesson content) in English and Indonesian. */
const dict = {
	en: {
		header: {
			home: 'ArrayLab home',
			learn: 'Learn',
			lab: 'Lab',
			tagline: 'Explore arrays. Understand tensors.',
			main: 'Main'
		},
		theme: {
			toDark: 'Switch to dark mode',
			toLight: 'Switch to light mode'
		},
		fullscreen: {
			unsupported: 'Fullscreen is not available in this browser',
			exit: 'Exit fullscreen',
			enter: 'Enter fullscreen'
		},
		lang: {
			toIndonesian: 'Switch to Bahasa Indonesia',
			toEnglish: 'Switch to English'
		},
		lesson: {
			chapter: 'Chapter',
			chooseChapter: 'Choose chapter',
			chapterN: (n: string) => `Chapter ${n}`,
			steps: 'Steps',
			tryThis: 'Try this',
			resetStep: 'Reset this step',
			remember: 'Remember:',
			stepNav: 'Step navigation',
			back: 'Back',
			next: 'Next',
			count: (i: number, n: number) => `${i} / ${n}`
		},
		workspace: {
			lesson: 'Lesson',
			arrayLab: 'Array lab',
			tools: 'Tools',
			inspector: 'Inspector',
			noProperties: 'Array properties appear here.'
		},
		tools: {
			array: { label: 'Array', description: 'See the array, its shape and its axes' },
			axis: { label: 'Axis', description: 'Reduce along an axis: sum, mean, max, …' },
			index: { label: 'Index', description: 'Select elements, rows, columns and slices' },
			reshape: { label: 'Reshape', description: 'reshape, transpose, flatten, ravel' },
			broadcast: { label: 'Broadcast', description: 'Combine arrays of different shapes' },
			vectorize: { label: 'Vectorize', description: 'Loops vs whole-array operations' },
			dtype: { label: 'dtype', description: 'Convert between data types' },
			views: { label: 'View/copy', description: 'Does b share memory with a? Write into b and see' },
			combine: { label: 'Combine', description: 'concatenate, stack and split arrays' },
			torch: { label: '→ PyTorch', description: 'The same array as a PyTorch tensor (PyTorch code is shown, not run)' },
			autograd: { label: 'Autograd', description: 'A computational graph: forward values and backward gradients' },
			pandas: { label: 'pandas', description: 'The array as a labeled pandas DataFrame' },
			code: { label: 'Your code', description: 'Visualize variables from the code editor' }
		},
		codePanel: {
			label: 'Code and output',
			views: 'Code views',
			ran: 'Code that ran',
			yours: 'Your code',
			editACopy: 'Edit a copy',
			run: 'Run',
			runTitle: 'Run (Ctrl/⌘ + Enter)',
			shareTitle: 'Copy a link that opens the Lab with this array, tool and code',
			share: 'Share',
			linkCopied: 'Link copied',
			copyCode: 'Copy code',
			stopTitle: 'Stops the running code by restarting Python (variables are cleared)',
			stop: 'Stop',
			showPanel: 'Show code panel',
			hidePanel: 'Hide code panel',
			copyThisLink: 'Copy this link:',
			close: 'Close',
			switchToTool: 'Switch to a tool to see the NumPy code it runs.',
			toolCodeLabel: 'Code generated by the current tool (read-only)',
			editorLabel: 'Python editor',
			output: 'Output',
			pythonOutput: 'Python output',
			noOutput: 'Ran without output. End with an expression (e.g. a.shape) to see its value.',
			pressRun: 'Press Run to execute your code.',
			outputHere: 'Output appears here.',
			pyodideTitle: (v: string) => `Pyodide ${v}`,
			statusReady: (py: string, np: string) => `Python ${py} · NumPy ${np}`,
			statusErrorMsg: 'Python failed to load',
			statusNotStarted: 'Python not started'
		},
		inspector: {
			propertiesOf: (name: string) => `Properties of ${name}`,
			waiting: 'waiting for NumPy…',
			shapeHelp: 'Length of each axis.',
			ndimHelp: 'Number of axes = number of entries in shape.',
			sizeHelp: 'Total number of elements = product of the shape.',
			dtypeHelp: 'Type of every element. One array has exactly one dtype.',
			itemsizeHelp: 'Bytes used by one element.',
			nbytesHelp: 'Bytes used by all elements = size × itemsize.',
			memoryHelp: 'Is the data stored in one block, in reading order (row-major)?',
			byte: (n: number) => `${n} byte${n === 1 ? '' : 's'}`,
			contiguous: 'C-contiguous',
			notContiguous: 'not contiguous',
			ownsData: 'owns data',
			view: 'view',
			int32Note: 'int32 is the default integer in this browser (32-bit WebAssembly). Desktop NumPy 2 on 64-bit systems uses int64.'
		},
		frameInspector: {
			shapeHelpSeries: 'Number of rows.',
			shapeHelpFrame: '(rows, columns).',
			ndimHelp: 'A DataFrame is always 2-D, a Series 1-D.',
			sizeHelp: 'Number of values = rows × columns. Labels are not counted.',
			indexHelp: 'Row labels. RangeIndex means the default labels 0, 1, 2 … (equal to the positions).',
			dtypeHelpSeries: 'A Series has one dtype.',
			nameHelp: 'The label a Series carries (e.g. its column name).',
			none: 'None',
			columnsHelp: 'Column labels.',
			dtypesHelp: 'Each column has its own dtype.',
			memoryHelp: 'Memory of the values, without the labels: memory_usage(index=False).',
			memory: 'memory'
		},
		errorCard: {
			originalError: 'Original Python error',
			try: 'Try:'
		},
		runStatus: {
			sharedLinkIntro: 'This shared link contains code that runs in this lab:',
			sharedLinkOnly: 'It runs only in your browser. Check it, then run it.',
			runIt: 'Run it',
			retry: 'Retry',
			pythonNotLoaded: (msg: string) =>
				`Python could not be loaded: ${msg}. ArrayLab downloads Python + NumPy (≈ 15 MB) from cdn.jsdelivr.net the first time — check your connection.`,
			startingPython: 'Starting Python…',
			firstVisit: '(first visit downloads ≈ 15 MB, then it is cached)',
			cached: '(downloaded once, then cached)',
			numpyWarned: 'NumPy warned:'
		},
		sourceInput: {
			howToCreate: 'How to create a',
			typeNumbers: 'Type numbers',
			numpyFunction: 'NumPy function',
			dtype: 'dtype',
			auto: 'auto (NumPy decides)',
			dtypeAria: 'dtype for the typed numbers',
			numbersAria: 'Numbers for array a',
			exampleNumbers: 'Example numbers',
			try: 'Try',
			help: 'Spaces or commas between values · new line = new row · blank line = new 2-D layer (3-D array).',
			exprAria: 'NumPy expression for a',
			run: 'Run',
			exampleExpressions: 'Example expressions',
			presets: { '1-D': '1-D', '2-D': '2-D', '3-D': '3-D', column: 'column', floats: 'floats', booleans: 'booleans' }
		},
		explain: {
			whatHappened: 'What happened'
		},
		home: {
			title: 'ArrayLab — Explore arrays. Understand tensors.',
			eyebrow: 'An interactive NumPy laboratory',
			h1a: 'Explore arrays.',
			h1b: 'Understand tensors.',
			lead: 'Type numbers and watch them become a real NumPy array — then reduce along axes, slice, reshape and broadcast, and see what NumPy does. Python runs right in your browser.',
			startChapter: 'Start chapter 01',
			openLab: 'Open the lab',
			howAria: 'How ArrayLab works',
			how1Strong: 'Type numbers',
			how1: ' — no Python needed to start.',
			how2Strong: 'See the ndarray',
			how2: ' — its grid, axes, shape and dtype.',
			how3Strong: 'Change something',
			how3: " — an axis, an index, a shape — and watch NumPy's answer.",
			tryAria: 'Try it: create an array',
			chapters: 'Chapters',
			pytorchTag: 'PyTorch',
			pytorchTitle: 'PyTorch code is shown next to live NumPy; run it in Colab',
			pandasTag: 'pandas',
			pandasTitle: 'Real pandas, running in your browser',
			footer1: 'ArrayLab runs Python and NumPy in your browser with',
			footer2: 'No server, no account — nothing you type leaves your computer. ·',
			sourceOnGithub: 'Source on GitHub'
		},
		learnPage: {
			titleSuffix: 'ArrayLab'
		},
		labPage: {
			title: 'Lab · ArrayLab',
			hiddenH1: 'ArrayLab — free lab'
		},
		arrayGrid: {
			moreColumnsNotShown: (n: string) => `${n} more columns not shown`,
			moreRowsNotShown: (n: string) => `${n} more rows not shown`,
			moreAlongAxis: (n: string, axis: number) => `+${n} more along axis ${axis}`,
			axes: 'Axes',
			scalar: 'scalar',
			truncated: (count: string, preview: string, full: string) => `Array has ${count} elements. Showing a ${preview} preview of ${full}.`
		},
		shapeView: {
			shapeOf: (name: string) => `Shape of ${name}`,
			ndimHelp: 'number of entries in the shape (number of axes)',
			totalElements: 'total elements',
			scalarHelp: 'a 0-d array holds exactly one value'
		},
		memoryBar: {
			label: (size: number, itemsize: number, nbytes: number) => `${size} elements × ${itemsize} bytes = ${nbytes} bytes`,
			element: (i: number, itemsize: number) => `element ${i}: ${itemsize} bytes`
		},
		shapeAlignment: {
			ariaLabel: 'Broadcasting shape alignment',
			equal: '✓ equal',
			stretch: '↔ 1 stretches',
			missing: '+ missing → 1',
			conflict: '✕ conflict',
			compatible: '✓ Compatible: every column is equal or has a 1 (or a missing dimension).',
			incompatible: '✕ Incompatible: at least one column has two different sizes and neither is 1.'
		},
		frameTable: {
			series: 'Series',
			dataFrame: 'DataFrame',
			truncated: (kind: string, rows: string, cols: string, shownRows: number, shownCols: string) =>
				`${kind} has ${rows} rows${cols ? ` × ${cols} columns` : ''}. Showing the first ${shownRows}${shownCols ? ` × ${shownCols}` : ''}.`,
			gridLabel: (name: string, kind: string, rows: number, cols: string) => `${name}: ${kind} with ${rows} rows${cols ? ` and ${cols} columns` : ''}`,
			noName: 'This Series has no name',
			position: (i: number) => `position ${i}`,
			moreColumns: (n: number) => `${n} more columns`,
			moreRows: (n: number) => `${n} more rows`
		},
		arrayView: {
			readingTheArray: 'Reading the array',
			hoverHint: 'Hover or focus a cell to see its index.',
			scalarExplain:
				'A single value makes a 0-d array: shape (), ndim 0, size 1. It has no axes to move along.',
			everyElement: (ndim: number, word: string) => `Every element has one index per axis — ${ndim} ${word}, because ndim is ${ndim}. The shape lists how long each axis is.`,
			number: 'number',
			numbers: 'numbers',
			axisLength: (axis: number, len: number, ord: string, extra: string) =>
				`has length ${len}: moving along it changes the ${ord} index${extra}`,
			steppingBetween: (role: string) => ` — you step between ${role}`,
			higherDimNote:
				'Rows and columns are only names for the last two axes. With more dimensions, count axes from the outside in: axis 0 selects the outermost block.'
		}
	},
	id: {
		header: {
			home: 'Beranda ArrayLab',
			learn: 'Belajar',
			lab: 'Lab',
			tagline: 'Jelajahi array. Pahami tensor.',
			main: 'Utama'
		},
		theme: {
			toDark: 'Beralih ke mode gelap',
			toLight: 'Beralih ke mode terang'
		},
		fullscreen: {
			unsupported: 'Mode layar penuh tidak tersedia di browser ini',
			exit: 'Keluar dari layar penuh',
			enter: 'Masuk ke layar penuh'
		},
		lang: {
			toIndonesian: 'Beralih ke Bahasa Indonesia',
			toEnglish: 'Switch to English'
		},
		lesson: {
			chapter: 'Bab',
			chooseChapter: 'Pilih bab',
			chapterN: (n: string) => `Bab ${n}`,
			steps: 'Langkah',
			tryThis: 'Coba ini',
			resetStep: 'Atur ulang langkah ini',
			remember: 'Ingat:',
			stepNav: 'Navigasi langkah',
			back: 'Kembali',
			next: 'Lanjut',
			count: (i: number, n: number) => `${i} / ${n}`
		},
		workspace: {
			lesson: 'Pelajaran',
			arrayLab: 'Lab array',
			tools: 'Alat',
			inspector: 'Inspektor',
			noProperties: 'Properti array muncul di sini.'
		},
		tools: {
			array: { label: 'Array', description: 'Lihat array, shape dan axis-nya' },
			axis: { label: 'Axis', description: 'Reduksi sepanjang sebuah axis: sum, mean, max, …' },
			index: { label: 'Indeks', description: 'Pilih elemen, baris, kolom dan irisan (slice)' },
			reshape: { label: 'Reshape', description: 'reshape, transpose, flatten, ravel' },
			broadcast: { label: 'Broadcast', description: 'Menggabungkan array dengan shape berbeda' },
			vectorize: { label: 'Vektorisasi', description: 'Loop vs operasi pada seluruh array' },
			dtype: { label: 'dtype', description: 'Konversi antar tipe data' },
			views: { label: 'View/copy', description: 'Apakah b berbagi memori dengan a? Tulis ke b dan lihat hasilnya' },
			combine: { label: 'Gabung', description: 'concatenate, stack dan split array' },
			torch: { label: '→ PyTorch', description: 'Array yang sama sebagai tensor PyTorch (kode PyTorch ditampilkan, tidak dijalankan)' },
			autograd: { label: 'Autograd', description: 'Graf komputasi: nilai forward dan gradien backward' },
			pandas: { label: 'pandas', description: 'Array sebagai DataFrame pandas berlabel' },
			code: { label: 'Kode kamu', description: 'Visualisasikan variabel dari editor kode' }
		},
		codePanel: {
			label: 'Kode dan output',
			views: 'Tampilan kode',
			ran: 'Kode yang dijalankan',
			yours: 'Kode kamu',
			editACopy: 'Edit salinan',
			run: 'Jalankan',
			runTitle: 'Jalankan (Ctrl/⌘ + Enter)',
			shareTitle: 'Salin tautan yang membuka Lab dengan array, alat dan kode ini',
			share: 'Bagikan',
			linkCopied: 'Tautan disalin',
			copyCode: 'Salin kode',
			stopTitle: 'Menghentikan kode yang berjalan dengan me-restart Python (variabel dihapus)',
			stop: 'Hentikan',
			showPanel: 'Tampilkan panel kode',
			hidePanel: 'Sembunyikan panel kode',
			copyThisLink: 'Salin tautan ini:',
			close: 'Tutup',
			switchToTool: 'Pindah ke sebuah alat untuk melihat kode NumPy yang dijalankannya.',
			toolCodeLabel: 'Kode yang dibuat oleh alat saat ini (hanya baca)',
			editorLabel: 'Editor Python',
			output: 'Output',
			pythonOutput: 'Output Python',
			noOutput: 'Berjalan tanpa output. Akhiri dengan sebuah ekspresi (mis. a.shape) untuk melihat nilainya.',
			pressRun: 'Tekan Jalankan untuk menjalankan kodemu.',
			outputHere: 'Output akan muncul di sini.',
			pyodideTitle: (v: string) => `Pyodide ${v}`,
			statusReady: (py: string, np: string) => `Python ${py} · NumPy ${np}`,
			statusErrorMsg: 'Python gagal dimuat',
			statusNotStarted: 'Python belum dijalankan'
		},
		inspector: {
			propertiesOf: (name: string) => `Properti ${name}`,
			waiting: 'menunggu NumPy…',
			shapeHelp: 'Panjang tiap axis.',
			ndimHelp: 'Jumlah axis = jumlah entri pada shape.',
			sizeHelp: 'Jumlah total elemen = hasil kali shape.',
			dtypeHelp: 'Tipe setiap elemen. Satu array memiliki tepat satu dtype.',
			itemsizeHelp: 'Byte yang digunakan oleh satu elemen.',
			nbytesHelp: 'Byte yang digunakan oleh semua elemen = size × itemsize.',
			memoryHelp: 'Apakah data disimpan dalam satu blok, dalam urutan baca (row-major)?',
			byte: (n: number) => `${n} byte`,
			contiguous: 'C-contiguous',
			notContiguous: 'tidak kontigu',
			ownsData: 'memiliki data',
			view: 'view',
			int32Note: 'int32 adalah integer bawaan di browser ini (WebAssembly 32-bit). NumPy 2 desktop pada sistem 64-bit menggunakan int64.'
		},
		frameInspector: {
			shapeHelpSeries: 'Jumlah baris.',
			shapeHelpFrame: '(baris, kolom).',
			ndimHelp: 'DataFrame selalu 2-D, Series 1-D.',
			sizeHelp: 'Jumlah nilai = baris × kolom. Label tidak dihitung.',
			indexHelp: 'Label baris. RangeIndex berarti label bawaan 0, 1, 2 … (sama dengan posisinya).',
			dtypeHelpSeries: 'Sebuah Series memiliki satu dtype.',
			nameHelp: 'Label yang dibawa sebuah Series (mis. nama kolomnya).',
			none: 'None',
			columnsHelp: 'Label kolom.',
			dtypesHelp: 'Setiap kolom memiliki dtype-nya sendiri.',
			memoryHelp: 'Memori nilai, tanpa label: memory_usage(index=False).',
			memory: 'memori'
		},
		errorCard: {
			originalError: 'Error Python asli',
			try: 'Coba:'
		},
		runStatus: {
			sharedLinkIntro: 'Tautan bersama ini berisi kode yang dijalankan di lab ini:',
			sharedLinkOnly: 'Kode ini hanya berjalan di browsermu. Periksa dulu, baru jalankan.',
			runIt: 'Jalankan',
			retry: 'Coba lagi',
			pythonNotLoaded: (msg: string) =>
				`Python gagal dimuat: ${msg}. ArrayLab mengunduh Python + NumPy (± 15 MB) dari cdn.jsdelivr.net saat pertama kali — periksa koneksimu.`,
			startingPython: 'Memulai Python…',
			firstVisit: '(kunjungan pertama mengunduh ± 15 MB, lalu disimpan dalam cache)',
			cached: '(diunduh sekali, lalu disimpan dalam cache)',
			numpyWarned: 'Peringatan NumPy:'
		},
		sourceInput: {
			howToCreate: 'Cara membuat a',
			typeNumbers: 'Ketik angka',
			numpyFunction: 'Fungsi NumPy',
			dtype: 'dtype',
			auto: 'otomatis (NumPy yang menentukan)',
			dtypeAria: 'dtype untuk angka yang diketik',
			numbersAria: 'Angka untuk array a',
			exampleNumbers: 'Contoh angka',
			try: 'Coba',
			help: 'Spasi atau koma antar nilai · baris baru = baris baru · baris kosong = lapisan 2-D baru (array 3-D).',
			exprAria: 'Ekspresi NumPy untuk a',
			run: 'Jalankan',
			exampleExpressions: 'Contoh ekspresi',
			presets: { '1-D': '1-D', '2-D': '2-D', '3-D': '3-D', column: 'kolom', floats: 'desimal', booleans: 'boolean' }
		},
		explain: {
			whatHappened: 'Apa yang terjadi'
		},
		home: {
			title: 'ArrayLab — Jelajahi array. Pahami tensor.',
			eyebrow: 'Laboratorium NumPy interaktif',
			h1a: 'Jelajahi array.',
			h1b: 'Pahami tensor.',
			lead: 'Ketik angka dan lihat angka itu menjadi array NumPy sungguhan — lalu reduksi sepanjang axis, iris (slice), ubah shape (reshape), dan broadcast, sambil melihat langsung apa yang dilakukan NumPy. Python berjalan langsung di browsermu.',
			startChapter: 'Mulai bab 01',
			openLab: 'Buka lab',
			howAria: 'Cara kerja ArrayLab',
			how1Strong: 'Ketik angka',
			how1: ' — tidak perlu Python untuk memulai.',
			how2Strong: 'Lihat ndarray-nya',
			how2: ' — grid, axis, shape dan dtype-nya.',
			how3Strong: 'Ubah sesuatu',
			how3: ' — sebuah axis, indeks, shape — lalu lihat jawaban NumPy.',
			tryAria: 'Coba langsung: buat sebuah array',
			chapters: 'Daftar Bab',
			pytorchTag: 'PyTorch',
			pytorchTitle: 'Kode PyTorch ditampilkan di samping NumPy yang berjalan langsung; jalankan di Colab',
			pandasTag: 'pandas',
			pandasTitle: 'pandas sungguhan, berjalan di browsermu',
			footer1: 'ArrayLab menjalankan Python dan NumPy di browsermu dengan',
			footer2: 'Tanpa server, tanpa akun — apa pun yang kamu ketik tidak meninggalkan komputermu. ·',
			sourceOnGithub: 'Kode sumber di GitHub'
		},
		learnPage: {
			titleSuffix: 'ArrayLab'
		},
		labPage: {
			title: 'Lab · ArrayLab',
			hiddenH1: 'ArrayLab — lab bebas'
		},
		arrayGrid: {
			moreColumnsNotShown: (n: string) => `${n} kolom lagi tidak ditampilkan`,
			moreRowsNotShown: (n: string) => `${n} baris lagi tidak ditampilkan`,
			moreAlongAxis: (n: string, axis: number) => `+${n} lagi sepanjang axis ${axis}`,
			axes: 'Axis',
			scalar: 'skalar',
			truncated: (count: string, preview: string, full: string) => `Array memiliki ${count} elemen. Menampilkan pratinjau ${preview} dari ${full}.`
		},
		shapeView: {
			shapeOf: (name: string) => `Shape dari ${name}`,
			ndimHelp: 'jumlah entri pada shape (jumlah axis)',
			totalElements: 'total elemen',
			scalarHelp: 'array 0-d menampung tepat satu nilai'
		},
		memoryBar: {
			label: (size: number, itemsize: number, nbytes: number) => `${size} elemen × ${itemsize} byte = ${nbytes} byte`,
			element: (i: number, itemsize: number) => `elemen ${i}: ${itemsize} byte`
		},
		shapeAlignment: {
			ariaLabel: 'Penyelarasan shape untuk broadcasting',
			equal: '✓ sama',
			stretch: '↔ 1 diregangkan',
			missing: '+ hilang → 1',
			conflict: '✕ konflik',
			compatible: '✓ Kompatibel: setiap kolom sama atau memiliki angka 1 (atau dimensi yang hilang).',
			incompatible: '✕ Tidak kompatibel: ada kolom dengan dua ukuran berbeda dan tidak satu pun bernilai 1.'
		},
		frameTable: {
			series: 'Series',
			dataFrame: 'DataFrame',
			truncated: (kind: string, rows: string, cols: string, shownRows: number, shownCols: string) =>
				`${kind} memiliki ${rows} baris${cols ? ` × ${cols} kolom` : ''}. Menampilkan ${shownRows} pertama${shownCols ? ` × ${shownCols}` : ''}.`,
			gridLabel: (name: string, kind: string, rows: number, cols: string) => `${name}: ${kind} dengan ${rows} baris${cols ? ` dan ${cols} kolom` : ''}`,
			noName: 'Series ini tidak memiliki nama',
			position: (i: number) => `posisi ${i}`,
			moreColumns: (n: number) => `${n} kolom lagi`,
			moreRows: (n: number) => `${n} baris lagi`
		},
		arrayView: {
			readingTheArray: 'Membaca array',
			hoverHint: 'Arahkan kursor atau fokus ke sebuah sel untuk melihat indeksnya.',
			scalarExplain:
				'Satu nilai tunggal membentuk array 0-d: shape (), ndim 0, size 1. Tidak ada axis untuk dilalui.',
			everyElement: (ndim: number, word: string) => `Setiap elemen memiliki satu indeks per axis — ${ndim} ${word}, karena ndim-nya adalah ${ndim}. Shape mendaftar seberapa panjang tiap axis.`,
			number: 'angka',
			numbers: 'angka',
			axisLength: (axis: number, len: number, ord: string, extra: string) =>
				`memiliki panjang ${len}: melangkah sepanjangnya mengubah indeks ${ord}${extra}`,
			steppingBetween: (role: string) => ` — kamu melangkah antar ${role}`,
			higherDimNote:
				'Baris dan kolom hanyalah nama untuk dua axis terakhir. Dengan dimensi lebih banyak, hitung axis dari luar ke dalam: axis 0 memilih blok paling luar.'
		}
	}
} as const;

export function t<K extends keyof (typeof dict)['en']>(section: K): (typeof dict)['en'][K] {
	return (dict[lang.current] as (typeof dict)['en'])[section];
}
